spring.application.name=mdp-server
spring:
autoconfigure:
exclude:
-org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration
-org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration

mqtt:
broker-url: tcp://localhost:1883
client-id: main-server-test
username:
password:
qos: 1
topics:
- mdp/pi/rpi-01/sensor/temperature