server.port=8080

#mqtt.broker=tcp://192.168.0.20:1883
#??? ??? ???
mqtt.broker-url=tcp://192.168.0.20:1883
mqtt.client-id=main-server
mqtt.qos=1
mqtt.topics[0]=mdp/sensor/#

db.server.url=http://192.168.0.21:7000
web.server.url=http://192.168.0.22:3000
ai.server.url=http://192.168.0.70:8000

media.server.base-url=http://192.168.0.20:8090
#????? ??? ??? ???
#media.server.base-url=http://127.0.0.1:8090
media.upload-dir=uploads

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yjc081230@gmail.com
spring.mail.password=kagc ritd vmwz ounb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
