server.port=8080

#mqtt.broker=tcp://192.168.0.20:1883
#??? ??? ???
mqtt.broker-url=tcp://localhost:1883
mqtt.client-id=main-server
mqtt.qos=1
mqtt.topics[0]=mdp/#

db.server.url=http://192.168.0.21:7000
web.server.url=http://192.168.0.22:3000
ai.server.url=http://192.168.0.40:8000

#media.server.base-url=http://192.168.0.20:8090
#????? ??? ??? ???
media.server.base-url=http://localhost:8090
media.upload-dir=uploads